# https://docs.codecov.io/docs/codecov-yaml
codecov:
  notify:
    require_ci_to_pass: no

# https://docs.codecov.io/docs/coverage-configuration
coverage:
  round: down
  precision: 2
  range: "80...100"

  status:
    # https://docs.codecov.io/docs/commit-status#section-project-status
    project:
      default:
        enabled: yes
        base: auto
        target: auto
        threshold: null
    # https://docs.codecov.io/docs/commit-status#section-patch-status
    patch:
      default:
        enabled: yes
        base: auto
        target: 90
        threshold: null
    # https://docs.codecov.io/docs/commit-status#section-changes-status
    changes: yes

#
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

# https://docs.codecov.io/docs/pull-request-comments
comment:
  behavior: default
  require_changes: yes
  layout: "header, reach, diff, files"
